name: CI PR/Branch
on:
  push:
    branches-ignore:
      - master
  pull_request:

env:
  PLUGIN_NAME: "homecentr/glusterfs-volume-plugin"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        
      - name: Set tag var
        id: vars
        run: echo ::set-output name=docker_tag::$(echo ${GITHUB_REF} | cut -d'/' -f3)-${GITHUB_SHA}

      - name: Verify Dockerfile with Hadolint
        uses: brpaz/hadolint-action@master      

      - name: Build Docker image
        run: docker build . -t ${{ env.PLUGIN_NAME }}:${{ steps.vars.outputs.docker_tag }}

      - name: Scan with Phonito Security
        uses: phonito/phonito-scanner-action@master
        with:
          image: ${{ env.PLUGIN_NAME }}:${{ steps.vars.outputs.docker_tag }}
          phonito-token: '${{ secrets.PHONITO_TOKEN }}'

      - name: Scan with Snyk
        uses: snyk/actions/docker@0.3.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ env.PLUGIN_NAME }}:${{ steps.vars.outputs.docker_tag }}

      - name: Build Docker plugin
        run: sudo sh ./build.sh "${{ steps.vars.outputs.docker_tag }}"

        # The property is still called docker_image_tag because the tests use the same resolver as normal image tests
      - name: Test Docker plugin
        run: cd tests && sudo gradle test --info -Ddocker_image_tag=${{ env.PLUGIN_NAME }}:${{ steps.vars.outputs.docker_tag }}
